import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import './assets/scss/plugins/_plugin-react-slick.scss';
import registerServiceWorker from './registerServiceWorker';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import "assets/scss/material-kit-pro-react.css?v=1.2.0";
ReactDOM.render( <App />, document.getElementById('root'));
registerServiceWorker();